
export enum EChatSocketAction {
	CONNECT_CHAT = '(CHAT)-CONNECT_CHAT',
	LOGIN_CHAT = '(CHAT)-LOGIN_CHAT',
	SEND_MSG = '(CHAT)-SEND_MSG',
	RECEIVE_MSG = '(CHAT)-RECEIVE_MSG',
	GET_CHAT_HISTORY = '(CHAT)-GET_CHAT_HISTORY',
	DISCONNECT_CHAT = '(CHAT)-DISCONNECT_CHAT',
}
