export enum EDashboardSocketAction {
  SUBSCRIBE_DASHBOARD = "(DASHBOARD)-SUBSCRIBE_DASHBOARD",
  CONNECT_DASHBOARD = "(DASHBOARD)-CONNECT_DASHBOARD",
  GET_DASHBOARD_HISTORY = "(DASHBOARD)-GET_DASHBOARD_HISTORY",
  DISCONNECT_DASHBOARD = "(DASHBOARD)-DISCONNECT_DASHBOARD",
  GET_TOP_PLAYERS = "(DASHBOARD)-GET_TOP_PLAYERS",
}
